source $HOME/.shared_profile

# Set up git autocomplete
plugins=(… zsh-completions)
autoload -U compinit && compinit

# Set up searching history with up and down arrows
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# Set up Ruby / rbenv
eval "$(rbenv init - zsh)"

# Source our config files.
source $HOME/source/FancyPantsPS1/fancypants_sharedrc && source $HOME/source/FancyPantsPS1/fancypants_ps1_zshprompt
source $HOME/.custom_zshrc
