name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  install:
    name: Install
    runs-on: macOS-14
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Prepare script
        run: mkdir -p $HOME/source/MagCat && cp -R . $HOME/source/MagCat
      - name: Run install script
        run: zsh <(curl -Ls https://raw.githubusercontent.com/dfed/MagCat/main/install.sh) --no-ui
