name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  install:
    name: Install
    runs-on: macOS-12
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run install script
        run: zsh <(curl -Ls https://raw.githubusercontent.com/dfed/MagCat/main/install.sh) --ci
